### ISSUE TITLE
Getting Stack over flow error

### ISSUE THREAD

**Issue by emilpradeep** [TooTallNate/Java-WebSocket#425]
E/AndroidRuntime: FATAL EXCEPTION: Thread-1415
                  Process: com.example, PID: 5182
                  java.lang.StackOverflowError
                      at com.android.org.conscrypt.OpenSSLCipher.getOutputSize(OpenSSLCipher.java:201)
                      at com.android.org.conscrypt.OpenSSLCipher.engineGetOutputSize(OpenSSLCipher.java:213)
                      at javax.crypto.Cipher.getOutputSize(Cipher.java:402)
                      at com.android.org.conscrypt.ConnectionState.getMinFragmentSize(ConnectionState.java:69)
                      at com.android.org.conscrypt.SSLRecordProtocol.getMinRecordSize(SSLRecordProtocol.java:134)
                      at com.android.org.conscrypt.SSLEngineImpl.unwrap(SSLEngineImpl.java:434)
                      at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:383)
                      at org.java_websocket.SSLSocketChannel2.unwrap(SSLSocketChannel2.java:150)
                      at org.java_websocket.SSLSocketChannel2.readRemaining(SSLSocketChannel2.java:254)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:220)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                      at org.java_websocket.SSLSocketChannel2.read(SSLSocketChannel2.java:241)
                  	at org.java_web

**Comment by marci4** [comment]
hey @emilpradeep,

could you tell me which version you use?
So I can try to reproduce it 

Greetings
marci4

**Comment by simonchius** [comment]
I am getting this issue too, I am using this version (org.java-websocket:Java-WebSocket:1.3.0).
Can anyone help?

**Comment by marci4** [comment]
Hello @simonchius, 
is it possible for you to send me your code please?

Right now I cannot reproduce it :(

Also try to build the jar directly from the sources. I merged some fixes there.

Greetings
marci4

**Comment by emilpradeep** [comment]
@marci4  @simonchius  please refer to #190 . I fixed the issue with @Erhannis solution

**Comment by marci4** [comment]
@emilpradeep do I understand you correct that this issue is fixed right now using the lastest sources?

Greetings
marci4

**Comment by emilpradeep** [comment]
yes, the issue is fixed for me.

**Comment by marci4** [comment]
Yes :)
Thx for the feedback =)

Greetings
marci4

**Comment by simonchius** [comment]
So as my understanding, If i update to latest version, this issue will be fixed. Am i right?

**Comment by marci4** [comment]
Right now there is no update available in the maven repository (I don't have access to it).

So you need to build the jar directly from the sources (see README)

Greetings

**Comment by marci4** [comment]
@simonchius I updated the readme with the new maven repository etc

Please check it out :)

Greetings
marci4

**Comment by simonchius** [comment]
@marci4 Thanks for the update, I will check out.

**Comment by simonchius** [comment]
<img width="1181" alt="screen shot 2017-04-04 at 9 14 07 am" src="https://cloud.githubusercontent.com/assets/8415885/24640742/23a9777a-1917-11e7-86b0-ec9a2f184d74.png">

@marci4 It seems org.java-websocket:java-websocket:1.3.2  is not resolved. Can you please check that?

**Comment by marci4** [comment]
Hello @simonchius,

a different user mentioned here that you maybe need to clear the cache of your IDE and restart it
[Check here](https://github.com/TooTallNate/Java-WebSocket/issues/450#issuecomment-291124267)

Hope this fixes it for you.
Greetings
marci4

**Comment by simonchius** [comment]
Hi @marci4 

I tried clear cache and restarting Android Studio. Nothing is working. Still not working.

**Comment by marci4** [comment]
hello @simonchius,

could you maybe add the following line to the start of your build
`apply plugin:'java'`

If this is not working, could you please send me your full build script.

Greetings
marci4

**Comment by simonchius** [comment]
Hi @marci4 

apply plugin:'java' is not compatible with Android.

You can check my build script


apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.0'

    defaultConfig {
        applicationId "com.xxxx.xxxxxxxxxxxxxx"

        minSdkVersion 19
        targetSdkVersion 23
        versionCode 35
        versionName "1.1.0"
        multiDexEnabled true;

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile files('libs/fullauth-api-java-client-1.1.1.jar')
    compile project(':FeedsLibrary')
    compile 'com.android.support:appcompat-v7:25.3.0'
    compile 'com.android.support:design:25.3.0'
    compile 'com.android.support:recyclerview-v7:25.3.0'
    compile 'org.java-websocket:java-websocket:1.3.2'
    compile 'com.google.android.gms:play-services-auth:9.0.2'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.google.android.gms:play-services-location:9.0.2'
    compile 'com.google.firebase:firebase-crash:9.0.2'
    compile 'com.google.firebase:firebase-messaging:9.0.2'
    compile 'com.squareup.picasso:picasso:2.5.2'
}

apply plugin: 'com.google.gms.google-services'

**Comment by marci4** [comment]
Hello @emilpradeep 

please add the following lines to your build script

`repositories {
    maven { url "http://clojars.org/repo" }
}`

Greetings
marci4

**Comment by simonchius** [comment]
Hi @marci4,

Issue with building gradle is fixed,

But setWebSocketFactory and DefaultSSLWebSocketClientFactory not found

mWebSocketClient.setWebSocketFactory( new DefaultSSLWebSocketClientFactory( sslContext ) );

Since I am using wss, It was throwing SSL exception, So I added SSL Context manually like below

SSLContext sslContext = null;
        try {
            sslContext = SSLContext.getInstance( "TLS" );
            sslContext.init( null, null, null ); // will use java's default key and trust store which is sufficient unless you deal with self-signed certificates
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }


        mWebSocketClient.setWebSocketFactory( new DefaultSSLWebSocketClientFactory( sslContext ) );

Now setWebSocketFactory and DefaultSSLWebSocketClientFactory not found..


Pls check this.

**Comment by marci4** [comment]
Hello, 
The code changed a bit with the internal commits. 

Check this example when you wanna use a ssl context. 
https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/SSLClientExample.java

Greetings 
Marci4

**Comment by marci4** [comment]
Issue is clearly solved.

Closing issue.
Greetings
marci4
